name: Deploy a simple application 
on: 
    push:
        branches:
        - master
jobs:
    deploy_application_job:
        runs-on: ubuntu-latest
        steps:
        - name: "say hello"
          run: |
            echo "Hello everyone!"
        - name: "List directory 1"
          run: |
            ls -la

        - name: Checkout from .github directory
          uses: actions/checkout@v4
          
        - name: "List directory 2"
          run: |
            ls -la

        - name: "Build Docker image"
          run: |
            docker build -t sampleapp124 .

        # - name: "Login to DockerHub"
        #   run: | 
        #     docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


        - name: "Push to DockerHub"
          run: | 
            docker push sampleapp124


        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1  # Change to your AWS region

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2


        - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: riceopy
          IMAGE_TAG: sampleapp124
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG